version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
permissions:
  - object: /home/ec2-user/build
    pattern: "*_server"
    owner: ec2-user
    group: ec2-user
    mode: 775
    type:
      - file
  - object: /home/ec2-user/build
    pattern: "*.jar"
    owner: ec2-user
    group: ec2-user
    type:
      - file
  - object: /home/ec2-user/build
    pattern: "*.yml"
    owner: ec2-user
    group: ec2-user
    type:
      - file
hooks:
  ApplicationStop:
    - location: stop_server
      runas: ec2-user
  ApplicationStart:
    - location: start_server
      runas: ec2-user
