version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - chmod +x gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew bootJar -x test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  files:
    - scripts/*
    - appspec.yml
    - build/libs/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'