logging:
  level:
    com.skmwizard: debug

server:
  port: 8010

aws:
  region: ap-northeast-2
  accessKeyId: AKIA3G2RCBQUJTXV2XX4
  secretAccessKey: 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
  cognito:
    userPoolId: ap-northeast-2_zI7QoQpeJ
    webclient:
      clientId: 15mhttfj4hsqd5oibc2dkcpso9

spring:
  data:
    mongodb:
      host: 13.124.131.93
      port: 27017
      username: administrator
      password: Admin1234!#
      database: user
      authentication-database: admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /users/api-docs