logging:
  level:
    com.skmwizard: debug

server:
  port: 8010

spring:
  data:
    mongodb:
      host: 3.35.103.177
      port: 27017
      username: administrator
      password: Admin1234!#
      database: user
      authentication-database: admin

aws:
  region: ap-northeast-2
  accessKeyId: AKIA3G2RCBQUONBUF6N7
  secretAccessKey: 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
  cognito:
    userPoolId: ap-northeast-2_zI7QoQpeJ
    webclient:
      clientId: 15mhttfj4hsqd5oibc2dkcpso9

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /users/api-docs