server:
  port: 8010

spring:
  data:
    mongodb:
      host: 3.35.103.177
      port: 27017
      username: administrator
      password: Admin1234!#
      database: user
      authentication-database: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_zI7QoQpeJ/.well-known/jwks.json

aws:
  region: ap-northeast-2
  accessKeyId: AKIA3G2RCBQUONBUF6N7
  secretAccessKey: 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
  cognito:
    userPoolId: ap-northeast-2_zI7QoQpeJ
    webclient:
      clientId: 15mhttfj4hsqd5oibc2dkcpso9

activemq:
  endpoint: ssl://b-68d2a44a-83f7-4767-8aee-38411988a5e7-1.mq.ap-northeast-2.amazonaws.com:8883
  username: skmagic-iot
  password: skmwizard250!
  client:
    id: device-message-client

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /users/api-docs