POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "ingu@test.com",
  "name": "고인구",
  "password": "qwer1234!!",
  "nickname": "마법사",
  "address" : "",
  "status" : "AUTH"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "ingu@test.com",
  "password": "qwer1234!!"
}