###
GET http://localhost:8010/users/ingu2@test.com
Content-Type: application/json

###
POST http://localhost:8010/signup
Content-Type: application/json

{
  "email": "ingu2@test.com",
  "name": "고인구",
  "password": "qwer1234!!",
  "phoneNumber": "01052342435",
  "status": "AUTH",
  "agreeList": [
    "EMAIL",
    "SNS"
  ]
}

###
POST http://localhost:8010/login
Content-Type: application/json

{
  "email": "ingu@test.com",
  "password": "qwer1234!!"
}

> {%
client.global.set("accessToken", response.body.accessToken)
client.global.set("refreshToken", response.body.refreshToken)
%}

###
POST http://localhost:8010/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###
POST http://localhost:8010/token/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
GET http://localhost:8010/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
PUT http://localhost:8010/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "ingu5@test.com",
  "name": "공2"
}

###
PUT http://localhost:8010/me/password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "currentPassword": "qwer1234!!",
  "newPassword": "qwer1234!"
}

###
https://skmagic.auth.ap-northeast-2.amazoncognito.com/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic

grant_type=refresh_token&
client_id=
refresh_token=REFRESH_TOKEN

